on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "openai-api-playground"
          directory: "out/"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
